### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by nao-enpg** [nao-enpg/Nishinari_Izakaya_Crawl#21]
MVPリリースのレビュー依頼を提出させていただきます。
お忙しいところ恐れ入りますが、どうぞよろしくお願いいたします。

## 各種情報
サービス名：西成泥酔旅行
サービスURL：https://nishinari-izakaya-crawl-60cb4832.koyeb.app/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー機能（Google アカウントによる認証）
- [x] マップ検索（Google Maps API）
- [x] タグ検索
- [x] 検索結果一覧・詳細ページ
- [x] マイページ
- [x] お気に入りリスト
- [x] 旅程表作成

### ユーザー機能（Google アカウントによる認証）
[![Image from Gyazo](https://i.gyazo.com/48e6d4ec4772b1ed6243281b54040f39.jpg)](https://gyazo.com/48e6d4ec4772b1ed6243281b54040f39)

### マップ検索（Google Maps API）・タグ検索
[![Image from Gyazo](https://i.gyazo.com/1167d5bccd27ee0d03b9ef7f3bb414bf.png)](https://gyazo.com/1167d5bccd27ee0d03b9ef7f3bb414bf)

### 検索結果一覧・詳細ページ
[![Image from Gyazo](https://i.gyazo.com/03d56afb929b5b7ac7716fca0594eff0.png)](https://gyazo.com/03d56afb929b5b7ac7716fca0594eff0)
[![Image from Gyazo](https://i.gyazo.com/ed9bd8f013d8037a0be0c4d9b00df530.png)](https://gyazo.com/ed9bd8f013d8037a0be0c4d9b00df530)

### マイページ（お気に入りリストを含む）
[![Image from Gyazo](https://i.gyazo.com/ea85ad50479d5675b1965145014619bc.png)](https://gyazo.com/ea85ad50479d5675b1965145014619bc)

### 旅程表作成
[![Image from Gyazo](https://i.gyazo.com/c5fbb16d868d4f7000707e9f1579e844.png)](https://gyazo.com/c5fbb16d868d4f7000707e9f1579e844)
[![Image from Gyazo](https://i.gyazo.com/b5e670af465cd33c10b283550f6413d0.png)](https://gyazo.com/b5e670af465cd33c10b283550f6413d0)

**Comment by shota-hope** [comment]
提出ありがとうございます。

- ログインしていない状態でTOP画面の呑みに行くボタンを押すとエラー画面になりました
- 検索画面の店舗一覧でいいねボタンを押すと`Content missing`という表示がされることがありました
  - [![Image from Gyazo](https://i.gyazo.com/1ed3242e20b0e52bc4e1b8f4a28bd458.jpg)](https://gyazo.com/1ed3242e20b0e52bc4e1b8f4a28bd458)
- その他機能確認できました

ご確認よろしくお願いします。

**Comment by nao-enpg** [comment]
早速ご確認くださりありがとうございます。
> ・ログインしていない状態でTOP画面の呑みに行くボタンを押すとエラー画面になりました

上記についてはコントローラーを修正しエラー解消いたしました。

> ・検索画面の店舗一覧でいいねボタンを押すとContent missingという表示がされることがありました

上記について、キャプチャの共有までありがとうございます。

```Content missing```とのことなので、店舗一覧をTurbo Frameで表示している部分に不具合が起きたものと予想しているのですが、複数アカウントでいいねの登録・解除を試したところ状況再現できませんでした...
恐れ入りますが、もう一度操作をお試しいただけますでしょうか...？

お忙しい中恐縮ですが、よろしくお願いいたします。

**Comment by ky0613** [comment]
> 複数アカウントでいいねの登録・解除を試したところ状況再現できませんでした...

自分の環境でも特に発生はしなかったので一旦は問題ないかと思います！

LGTMです！
技術面でのアピール強化として、アプリ開発カリキュラムの「高度な機能」を検討してみましょう！
https://school.runteq.jp/v3/curriculums/application_development/chapters/6

**Comment by nao-enpg** [comment]
ありがとうございます！
本リリースに向けてUI・UXの改善と機能追加を引き続き頑張って参ります！！
