### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by nao-enpg** [nao-enpg/Nishinari_Izakaya_Crawl#22]
[Github Projects](https://github.com/users/nao-enpg/projects/2/)を利用しIssueを整理いたしました。
レビューの程よろしくお願いいたします。

## 実装予定の機能
- [x] ユーザー機能（Google アカウントによる認証）
- [x] マップ検索（Google Maps API）
- [x] タグ検索
- [x] 検索結果一覧・詳細ページ
- [x] マイページ
- [x] お気に入りリスト
- [x] 旅程表作成

## 必要なページ
- [x] トップページ
- [x] 検索ページ
- [x] 店舗詳細情報（モーダル）
- [x] マイページ
- [x] 旅程表作成ページ
- [x] 旅程表一覧ページ

**Comment by nao-enpg** [comment]
こちらにコメントで失礼いたします。
issue提出前に、カリキュラム画面でリポジトリURLを連携登録するべきところ、誤って本issueのURLを登録してしまいました。
大変申し訳ございませんが、カリキュラム画面の「スケジュール・Issue管理機能タブ」に反映をお願いできますでしょうか...？

Mattermostの運営相談チャンネルにてご報告したほうがよろしければ、そのようにさせていただきます。
お忙しいところ恐れ入りますが、どうぞよろしくお願いいたします。

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
この課題はLGTMです！

> Mattermostの運営相談チャンネルにてご報告したほうがよろしければ、そのようにさせていただきます。
お忙しいところ恐れ入りますが、どうぞよろしくお願いいたします。

登録して欲しいリポジトリURLをご提示の上、上記の対応でお願いできればと思います。
よろしくお願いします。

**Comment by nao-enpg** [comment]
ありがとうございます！
承知いたしました！
